### PR TITLE
Ensure Azure Backend Pool resource name will have 80 characters

### LINKED ISSUE #125: Cannot create new ingress due to invalid length
**Describe the bug**
When trying to create a new ingress, I receive the following error.

`Resource name k8s-ag-ingress-api-turnouttuserapi-80-bp-80-turnoutt-services-ingress-dev-1520020d is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'.`

Is there any way to shorten the name down?

**To Reproduce**

1. Configure the Gateway and Ingress as specified.
2. Create a new ingress.

**Ingress Controller details**
* Output of `kubectl describe pod <ingress controller`> . The <ingress controller> pod name can be obtained by running `helm list`. 
```
Name:               foolhardy-albatross-ingress-azure-65dfdbb775-nfcpm
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               aks-agentpool-32228829-3/10.241.0.97
Start Time:         Mon, 08 Apr 2019 08:50:49 -0700
Labels:             aadpodidbinding=foolhardy-albatross-ingress-azure
                    app=ingress-azure
                    pod-template-hash=65dfdbb775
                    release=foolhardy-albatross
Annotations:        <none>
Status:             Running
IP:                 10.241.0.123
Controlled By:      ReplicaSet/foolhardy-albatross-ingress-azure-65dfdbb775
Containers:
  ingress-azure:
    Container ID:   docker://953951014b81b426564c28289ef1e902e10c939ddc7e34eda2db3a74f1ad0e7f
    Image:          mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0
    Image ID:       docker-pullable://mcr.microsoft.com/azure-application-gateway/kubernetes-ingress@sha256:c110f441f81fc53060d4a88367ca9430c681e9a513cc978d55bed8c9025e9121
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 08 Apr 2019 08:50:57 -0700
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      foolhardy-albatross-cm-ingress-azure  ConfigMap  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from foolhardy-albatross-sa-ingress-azure-token-qxtcl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  foolhardy-albatross-sa-ingress-azure-token-qxtcl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  foolhardy-albatross-sa-ingress-azure-token-qxtcl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age   From                               Message
  ----    ------     ----  ----                               -------
  Normal  Scheduled  10m   default-scheduler                  Successfully assigned default/foolhardy-albatross-ingress-azure-65dfdbb775-nfcpm to aks-agentpool-32228829-3
  Normal  Pulling    10m   kubelet, aks-agentpool-32228829-3  pulling image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0"
  Normal  Pulled     10m   kubelet, aks-agentpool-32228829-3  Successfully pulled image "mcr.microsoft.com/azure-application-gateway/kubernetes-ingress:0.3.0"
  Normal  Created    10m   kubelet, aks-agentpool-32228829-3  Created container
  Normal  Started    10m   kubelet, aks-agentpool-32228829-3  Started container
```
* Output of `kubectl logs <ingress controller>. 

```
ERROR: logging before flag.Parse: W0408 15:51:02.875764       1 controller.go:105] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceName" Message="Resource name k8s-ag-ingress-api-turnouttuserapi-80-bp-80-turnoutt-services-ingress-dev-1520020d is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]]
ERROR: logging before flag.Parse: I0408 15:51:02.876025       1 controller.go:106] ~~~~~~~~ ↑ ApplicationGateway deployment ↑ ~~~~~~~~
ERROR: logging before flag.Parse: I0408 15:51:02.876044       1 eventqueue.go:126] Processing event failed
ERROR: logging before flag.Parse: I0408 15:51:02.876055       1 eventqueue.go:119] Processing event begin, time since event generation: 2.717826788s
ERROR: logging before flag.Parse: I0408 15:51:02.876060       1 controller.go:50] controller.processEvent called with type k8scontext.Event
ERROR: logging before flag.Parse: I0408 15:51:02.911702       1 backendhttpsettings.go:86] resolving port name http
ERROR: logging before flag.Parse: I0408 15:51:02.911730       1 backendhttpsettings.go:86] resolving port name http
ERROR: logging before flag.Parse: I0408 15:51:02.911740       1 backendhttpsettings.go:86] resolving port name http
ERROR: logging before flag.Parse: I0408 15:51:02.911933       1 backendhttpsettings.go:86] resolving port name http
ERROR: logging before flag.Parse: I0408 15:51:02.911964       1 backendhttpsettings.go:86] resolving port name http
ERROR: logging before flag.Parse: I0408 15:51:02.912149       1 controller.go:98] ~~~~~~~~ ↓ ApplicationGateway deployment ↓ ~~~~~~~~
ERROR: logging before flag.Parse: W0408 15:51:03.016742       1 controller.go:105] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceName" Message="Resource name k8s-ag-ingress-api-turnouttuserapi-80-bp-80-turnoutt-services-ingress-dev-1520020d is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]]
ERROR: logging before flag.Parse: I0408 15:51:03.016766       1 controller.go:106] ~~~~~~~~ ↑ ApplicationGateway deployment ↑ ~~~~~~~~
ERROR: logging before flag.Parse: I0408 15:51:03.016798       1 eventqueue.go:126] Processing event failed
```
* Any Azure support tickets associated with this issue.

### PR DESCRIPTION
**Pull request by marceldiass**
# Ensure 80 characters to Azure Backend pool resource name

## Why

I got errors to setup the environment my environment using Azure Application Gateway. 
Application gateway logs
```
ERROR: logging before flag.Parse: I0417 00:04:41.462075       1 controller.go:98] ~~~~~~~~ ↓ ApplicationGateway deployment ↓ ~~~~~~~~
ERROR: logging before flag.Parse: W0417 00:04:41.617271       1 controller.go:105] unable to send CreateOrUpdate request, error [network.ApplicationGatewaysClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidResourceName" Message="Resource name k8s-ag-ingress-ktn-cm-acme-http-solver-j7sxh-8089-bp-8089-cm-acme-http-solver-t8rnf is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'." Details=[]]
ERROR: logging before flag.Parse: I0417 00:04:41.617341       1 controller.go:106] ~~~~~~~~ ↑ ApplicationGateway deployment ↑ ~~~~~~~~
```

For this case it Cert-Manager ingress trying to register the service and pod to issue the SSL certificate, but I got the same error if my own application service name is longer than 14 chars

## What

I have implemented the logic to the last section of service name and ingress. 
Example: 
serviceName = `cm-acme-http-solver-j7sxh` 
will be replaced by `j7sxh`

This way it will limit the Backend pool to less than 80 characters and also should avoid the naming conflicts.

Also implemented test to ensure that behavior.

## Fix 
Should fix #125

### CODE REVIEW

File: pkg/appgw/internaltypes.go [hunk 1]
```diff
@@ -70,7 +70,13 @@ func getResourceKey(namespace, name string) string {
 }
 
 func generateHTTPSettingsName(serviceName string, servicePort string, backendPortNo int32, ingress string) string {
```
Comment (asridharan) [inline pkg/appgw/internaltypes.go]: It looks like the logic here is to simply truncate the name to less than 80 characters. This is pretty error prone since now you can lead to collisions in names. We probably need a more novel strategy to generate names for each of the sub resource in order to avoid name collisions and still maintain a character limit of 80 characters.

Comment (cwoolum) [reply pkg/appgw/internaltypes.go]: The last section of the deployment/ingress name is always unique isn't it? You could just pull the unique piece using a regex like `\-([a-z1-9]*)$`. In the test, the name would be `k8s-ag-ingress-j7sxh-8089-bp-8089-t8rnf`.

Comment (marceldiass) [reply pkg/appgw/internaltypes.go]: I liked the approach suggested by @cwoolum.  I have implemented it and updated the PR.

Comment (draychev) [reply pkg/appgw/internaltypes.go]: @cwoolum That's true for the pod names, but I'm not so sure about service and ingress. 

To illustrate this I added the log line here: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/171 and cherry-picked the change in this PR.

For example - here is a set of test services I have on my AKS at the moment:
```
$ kubectl get service

NAME                      TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
frontend                  ClusterIP   10.2.61.105    <none>        80/TCP     10d
kubernetes                ClusterIP   10.2.0.1       <none>        443/TCP    10d
liveliness-test-service   ClusterIP   10.2.250.203   <none>        80/TCP     31h
redis-master              ClusterIP   10.2.66.56     <none>        6379/TCP   10d
```

And here are the ingress controllers:
```
$ kubectl get ingress

NAME                         HOSTS                 ADDRESS   PORTS     AGE
guestbook                    xx.mis.li,yy.mis.li             80, 443   6d15h
test-health-probes-ingress   xx.mis.li,yy.mis.li             80, 443   31h
```

And the log line indicates:  `I0511 23:31:17.313761   11190 backendhttpsettings.go:141] Created a new HTTP setting w/ name: k8s-ag-ingress-service-80-bp-8081-ingress`

The name constructed is `k8s-ag-ingress-service-80-bp-8081-ingress` -- we took `service` from `liveliness-test-service` and `ingress` from `test-health-probes-ingress`.

**Comment by draychev** [comment]
@marceldiass @cwoolum Thank you so much for your work on this!  I especially appreciate the fact that you have a solid test for the code change.
Would you mind if we incorporate the technique used here: https://github.com/Azure/application-gateway-kubernetes-ingress/pull/175 into your PR?

We can wrap the output of `generateHTTPSettingsName` with the new [governor](https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/appgw/internaltypes.go#L56-L68) function.

Here is an example: https://github.com/Azure/application-gateway-kubernetes-ingress/blob/master/pkg/appgw/internaltypes.go#L94-L96

**Comment by marceldiass** [comment]
hey @draychev,

Yes, that looks good to me. Please go ahead with `governor` function.  😄

**Comment by marceldiass** [comment]
hey folks,  thanks for accepting and merging it!
